version: '3.8'

services:
  freelancer-server:
    build: .
    container_name: freelancer-server
    network_mode: host
    environment:
      - SERVER_NAME=My Freelancer Server
      - SERVER_DESCRIPTION=Dies ist ein automatisierter Freelancer-Server.
      - SERVER_PASSWORD=geheimespasswort
      - ALLOW_NEW_PLAYERS=1
      - ENABLE_INTERNET=1
      - PLAYER_CAN_FIGHT=1
      - MAX_PLAYERS=16
      - ISO_URL="" #url für den iso-download, falls local, siehe volumes!
    ports:
      - "2302:2302/udp"
      - "6080:6080"
    volumes:
      - ./freelancer-data:/data
#      - ./Freelancer.iso:/opt/freelancer/Freelancer.iso
    networks:
      macvlan_net:
        ipv4_address: 192.168.178.210  # Die gewünschte IP-Adresse des Containers

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0 #anpassen!
    ipam:
      config:
        - subnet: 192.168.178.0/24 #anpassen!
          ip_range: 192.168.178.200/28 #range anpassen!
          gateway: 192.168.178.1 #gateway anpassen!
